# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateFirstWin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('summoner_id', models.CharField(max_length=10)),
                ('first_win_time', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='estimatefirstwin',
            unique_together=set([('summoner_id', 'region')]),
        ),
    ]
