# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWin', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estimatefirstwin',
            unique_together=set([('summoner_name', 'region')]),
        ),
    ]
