# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstWin', '0002_auto_20160502_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10, unique=True)),
                ('next_check_time', models.DateField()),
            ],
        ),
    ]
