# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionMastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_level', models.IntegerField()),
                ('champion_points', models.IntegerField()),
                ('chest_granted', models.BooleanField()),
                ('highest_grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('winner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_used', models.BooleanField(default=False)),
                ('match_priority', models.IntegerField(default=1)),
                ('role', models.CharField(max_length=100)),
                ('lane', models.CharField(max_length=100)),
                ('queue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Summoners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_id', models.CharField(max_length=100, unique=True)),
                ('summoner_priority', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='champions',
            name='champion_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Champions', to_field='champion_id'),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Match', to_field='match_id'),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='summoner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_0', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_1', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_2', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_3', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_4', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_5', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_6', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_7', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_8', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='match',
            name='summoner_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_9', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AddField(
            model_name='championmastery',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Champions', to_field='champion_id'),
        ),
        migrations.AddField(
            model_name='championmastery',
            name='summoner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
    ]
