# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0002_auto_20160504_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoners',
            name='summoner_used',
            field=models.BooleanField(default=False),
        ),
    ]
