# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0003_summoners_summoner_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoners',
            name='region',
            field=models.CharField(default='na', max_length=10),
        ),
    ]
