# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0004_summoners_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='summoner_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_0', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_1', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_2', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_3', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_4', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_5', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_6', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_7', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_8', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_9', to='ChampionMastery.Summoners', to_field='summoner_id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.NullBooleanField(),
        ),
    ]
