# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0006_apiusage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='championmastery',
            unique_together=set([('champion', 'summoner_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='matchlist',
            unique_together=set([('summoner_id', 'match_id')]),
        ),
    ]
