# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0007_auto_20160506_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='region',
            field=models.CharField(default='na', max_length=10),
        ),
    ]
