# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0008_matchlist_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='championmastery',
            name='region',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='championmastery',
            name='summoner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_0', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_1', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_2', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_3', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_4', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_5', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_6', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_7', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_8', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoner_9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summoner_9', to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Match'),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='region',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='summoner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChampionMastery.Summoners'),
        ),
        migrations.AlterField(
            model_name='summoners',
            name='region',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='summoners',
            name='summoner_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='championmastery',
            unique_together=set([('champion', 'summoner_id', 'region')]),
        ),
    ]
