# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0009_auto_20160507_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summoners',
            name='summoner_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('match_id', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='matchlist',
            unique_together=set([('summoner_id', 'match_id', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='summoners',
            unique_together=set([('summoner_id', 'region')]),
        ),
    ]
