# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChampionMastery', '0011_auto_20160507_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='api_hash',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='region',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
